### PR TITLE
Revamp design

### PR DESCRIPTION
**Pull request by kdsch**
Broadly, I want to make the design more accessible and clean up implementation as I go. I freely made changes. I welcome feedback and corrections.

**Design improvements**

- Limit line length to 2 to 3 alphabets
- Reduce use of solid rectangles
- Gently adapt font size and white space to screen width, accommodating mobile devices
- Simplify the newsletter signup form
- Use a little color

**Implementation improvements**

- Factor out inline CSS
- Reduce unnecessary use of Hugo abstractions, particularly partial templates
- Remove unused code. At the time of writing, I have not removed everything that I know to be unused.

### CODE REVIEW

**Comment by kdsch** [comment]
The main improvement on mobile: clearer menu and the entire form is above the fold.

## iPhone 6 old
image

## iPhone 6 new
image

**Comment by cbrake** [comment]
@kdsch text/fonts looks much cleaner. 

What does the little circle mean by links?

I like the arrows next to menu options that take you offsite.

Underline of menu options is clean and nice.

(Disclaimer -- I'm not a designer, so be patient with me :-) )

A few thoughts:

* I was hoping to add more to the home page, so I'm not sure how important it is to keep everything above the fold. Examples of other OSS projects sites. 
  * https://elm-lang.org/
  * https://kubernetes.io/
  * https://istio.io/
  * https://www.yoctoproject.org/
  * https://www.terraform.io/
* what do you think of trying to keep the logo? Again, I'm not a designer, so if you think it is lame and we are better off without it, please be open.

Of the examples above, I probably like the elm site about the best. Are there any sites you know of that would be good examples to pattern after?

I'll merge and deploy what you have done so far, and we can go from there.

**Comment by kraj** [comment]
good improvements I must say, I think small logo would be good to have perhaps, but I am also in same boat at Cliff ( He is my designer guru)

**Comment by cbrake** [comment]
lets continue design discussion @ #6

**Pull request merged**
